Update Puma to 6.0
After upgrading to Rails 7.1 we have this error:

StandardError: Puma 5 is not compatible with Rack 3, please upgrade to Puma 6 or higher.